### PR TITLE
Make it runnable on Linux for npm newbie

### PR DESCRIPTION
**Pull request by christophknabe**
I solved some issues when trying to run Trellis UI on my Ubuntu 18.04. I documented one more necessary step for downloading the dependencies, allowed `npm` to insert the target brower list, and finally resolved an import problem which came from file name case sensitivity on Linux.
Now it runs OK. Will test it more intensely on Monday.

### CODE REVIEW

**Review by acoburn — APPROVED** [review]
LGTM

**Comment by acoburn** [comment]
Thanks @ChristophKnabe. This code hasn't received a whole lot of attention recently, so if you have particular feature that you would like to add, feel free to make suggestions or send along PRs.

**Comment by christophknabe** [comment]
Hello @acoburn, thanks for accepting the PR.
In fact I am trying to connect a Solid App with authentication to the Trellis LDP server, and wanted to look into the Trellis UI, how it does that. But it seems to me, that Trellis UI does not use authentication.

**Comment by acoburn** [comment]
@ChristophKnabe that is correct -- Trellis supports basic auth and OIDC-based authentication. Solid defines its own authentication mechanism, which extends the typical OIDC flow.

**Pull request merged**
